// Auto-generated by set-env.js — do not edit manually.
// Run `npm run build` to regenerate with REALTIME_URL and GOOGLE_MAPS_API_KEY env vars.
export const environment = {
  production: true,
  googleMapsApiKey: '',
  realtimeUrl: 'http://localhost:3001',
};
