// Auto-generated by set-env.js — do not edit manually.
// Run `npm run build` to regenerate with REALTIME_URL and GOOGLE_MAPS_API_KEY env vars.
export const environment = {
  production: true,
  googleMapsApiKey: '',
  realtimeUrl: 'https://ws.logiflow.app',
  apiUrl: 'https://api.logiflow.app/api/v1',
  driverAppUrl: 'https://app.logiflow.app/route',
};
