#!/usr/bin/env node
/**
 * Generates environment.prod.ts before ng build.
 *
 * Usage:
 *   node src/environments/set-env.js && ng build
 *   (called automatically via `npm run build`)
 *
 * Environment variables:
 *   REALTIME_URL        — Socket.io gateway URL  (default: http://localhost:3001)
 *   GOOGLE_MAPS_API_KEY — Google Maps API key    (default: empty string)
 */

const { writeFileSync } = require('fs');
const { join } = require('path');

const realtimeUrl = process.env.REALTIME_URL || 'http://localhost:3001';
const googleMapsApiKey = process.env.GOOGLE_MAPS_API_KEY || '';

const content = [
  '// Auto-generated by set-env.js — do not edit manually.',
  '// Run `npm run build` to regenerate with REALTIME_URL and GOOGLE_MAPS_API_KEY env vars.',
  'export const environment = {',
  '  production: true,',
  `  googleMapsApiKey: '${googleMapsApiKey}',`,
  `  realtimeUrl: '${realtimeUrl}',`,
  '};',
  '',
].join('\n');

const outputPath = join(__dirname, 'environment.prod.ts');
writeFileSync(outputPath, content, 'utf8');
console.log(`✓ environment.prod.ts generated — REALTIME_URL=${realtimeUrl}`);
