#!/usr/bin/env node
/**
 * Generates environment.prod.ts before ng build.
 *
 * Usage:
 *   node src/environments/set-env.js && ng build
 *   (called automatically via `npm run build`)
 *
 * Environment variables (set in apps/web-admin/.env — gitignored):
 *   REALTIME_URL        — Socket.io gateway URL  (default: http://localhost:3001)
 *   GOOGLE_MAPS_API_KEY — Google Maps API key    (default: empty string)
 *   API_URL             — Gateway REST API URL    (default: http://localhost:3002/api/v1)
 *   DRIVER_APP_URL      — Driver app route URL    (default: http://localhost:8100/route)
 */

const { writeFileSync, existsSync, readFileSync } = require('fs');
const { join } = require('path');

// Load apps/web-admin/.env if present — never commit that file, put your API keys there
const localEnv = join(__dirname, '../../.env');
if (existsSync(localEnv)) {
  readFileSync(localEnv, 'utf8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const eq = trimmed.indexOf('=');
      if (eq === -1) return;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim();
      if (key && !(key in process.env)) process.env[key] = val;
    });
}

const realtimeUrl = process.env.REALTIME_URL || 'http://localhost:3001';
const googleMapsApiKey = process.env.GOOGLE_MAPS_API_KEY || '';
const apiUrl = process.env.API_URL || 'http://localhost:3002/api/v1';
const driverAppUrl = process.env.DRIVER_APP_URL || 'http://localhost:8100/route';

const content = [
  '// Auto-generated by set-env.js — do not edit manually.',
  '// Run `npm run build` to regenerate with env vars from apps/web-admin/.env',
  'export const environment = {',
  '  production: true,',
  `  googleMapsApiKey: '${googleMapsApiKey}',`,
  `  realtimeUrl: '${realtimeUrl}',`,
  `  apiUrl: '${apiUrl}',`,
  `  driverAppUrl: '${driverAppUrl}',`,
  '};',
  '',
].join('\n');

const outputPath = join(__dirname, 'environment.prod.ts');
writeFileSync(outputPath, content, 'utf8');
console.log(`✓ environment.prod.ts generated — REALTIME_URL=${realtimeUrl} API_URL=${apiUrl}`);
